on:
  push:
    branches:
      - slave





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      - uses: actions/checkout@v3
      
      -name: "Login to Docker hub"
        run:docker login --username ${{ secrete.DOCKER6_USERNAME }} --password ${{ secrete.DOCKER_TOCKEN }}


      - name: 'Testing Printing'
        run: echo Tasneem

