on:
  push:
    branches:
      - slave





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v3


      - name: 'After'
        run: ls

      - name: 'Testing Printing'
        run: echo Tasneem

