on:
  push:
    branches:
      - slave





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github Action'
        run: pwd


      - name: 'Testing Printing'
        run: echo Tasneem

