on:
  push:
    branches:
      - slave





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      - uses: actions/checkout@v3
      
      -name: "Login to Docker hub"
        run:docker login --username tasneem98100 --password dckr_pat_4rxE8Kd19LeseGBfIrHlIGwiLIc


      - name: 'Testing Printing'
        run: echo Tasneem

